### ISSUE TITLE
dense_slam_gui.py and Realsense l515 Error: Singular 6x6 linear system detected, tracking failed.

### ISSUE THREAD

**Issue by olagt** [isl-org/Open3D#4678]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When I run example Open3D/examples/python/t_reconstruction_system/./dense_slam_gui.py with test data ie. indoor_apartment  then it works properly.
But when I collect data using real-sense l515 with:
  python3 realsense_recorder.py --record_imgs --output_folder ./roomA01022022/
with stream definition :
config.enable_stream(rs.stream.depth, 1024, 768, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 1280, 720, rs.format.bgr8, 30)
then program crashes  at first frames with error 

RuntimeError: [Open3D Error] (void open3d::t::pipelines::kernel::DecodeAndSolve6x6(const open3d::core::Tensor&, open3d::core::Tensor&, float&, int&)) /home/ola/Proj2/Open3D/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp:145: Singular 6x6 linear system detected, tracking failed.

<pre>(Open3D14_1) <font color="#4E9A06"><b>ola@ola-ASUS-AI</b></font>:<font color="#3465A4"><b>~/Proj2/Open3D/examples/python/t_reconstruction_system</b></font>$ python ./dense_slam_gui.py --config /media/ola/Int2TB/AI_DATA3/RS_IK/roomA_trunc/roomA_trunc.yml 
FEngine (64 bits) created at 0x7f777a3a9010 (threading is enabled)
FEngine resolved backend: OpenGL
Exception in thread UpdateMain:
Traceback (most recent call last):
  File &quot;/usr/lib/python3.8/threading.py&quot;, line 932, in _bootstrap_inner
    self.run()
  File &quot;/usr/lib/python3.8/threading.py&quot;, line 870, in run
    self._target(*self._args, **self._kwargs)
  File &quot;./dense_slam_gui.py&quot;, line 375, in update_main
    result = self.model.track_frame_to_model(
RuntimeError: <font color="#CC0000"><b>[Open3D Error] (void open3d::t::pipelines::kernel::DecodeAndSolve6x6(const open3d::core::Tensor&amp;, open3d::core::Tensor&amp;, float&amp;, int&amp;)) /home/ola/Proj2/Open3D/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp:145: Singular 6x6 linear system detected, tracking failed.</b></font>

</pre>

I tried it with multiple recording with different resolution - but the error stays .
I also record almost static scenario when sensor is no moving - same error.
Depth Scale is set according to real sense sensor - 4000  ( depth_scale = depth_sensor.get_depth_scale() )

It crashes either with CPU:0 /  CUDA:0

![image](https://user-images.githubusercontent.com/38180749/151959688-36e8de10-32c2-4344-998c-8ca6258f7e7a.png)

### Steps to reproduce the bug

```python
1) collect data using realsense_recorder with l515 connected
2) modyfie yml exmaple config replacing depth_scale from 1000 to 4000 
3) run python ./dense_slam_gui.py --config media/ola/Int2TB/AI_DATA3/RS_IK/roomA_trunc/roomA_trunc.yml 
4) programs crashes 



name: Default reconstruction system config
fragment_size: 100
device: CUDA:0
engine: tensor
multiprocessing: false
path_dataset: '/media/ola/Int2TB/AI_DATA3/RS_IK/roomA_trunc'
depth_folder: depth
color_folder: color
path_intrinsic: '/media/ola/Int2TB/AI_DATA3/RS_IK/roomA_trunc/camera_intrinsic.json'
depth_min: 0.1
depth_max: 3.0
depth_scale: 4000.0
odometry_method: hybrid
odometry_loop_interval: 10
odometry_loop_weight: 0.1
odometry_distance_thr: 0.07
icp_method: colored
icp_voxelsize: 0.05
icp_distance_thr: 0.07
global_registration_method: ransac
registration_loop_weight: 0.1
integration_mode: color
voxel_size: 0.0058
sdf_trunc: 0.04
block_count: 40000
surface_weight_thr: 3.0
```

### Error message

(Open3D14_1) ola@ola-ASUS-AI:~/Proj2/Open3D/examples/python/t_reconstruction_system$ python ./dense_slam_gui.py --config /media/ola/Int2TB/AI_DATA3/RS_IK/roomA_trunc/roomA_trunc.yml 
FEngine (64 bits) created at 0x7f577db02010 (threading is enabled)
FEngine resolved backend: OpenGL
Exception in thread UpdateMain:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./dense_slam_gui.py", line 375, in update_main
    result = self.model.track_frame_to_model(
RuntimeError: [Open3D Error] (void open3d::t::pipelines::kernel::DecodeAndSolve6x6(const open3d::core::Tensor&, open3d::core::Tensor&, float&, int&)) /home/ola/Proj2/Open3D/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp:145: Singular 6x6 linear system detected, tracking failed.

Saving model to output.npz...
Finished.
Extracting and saving mesh to output.ply...
[Open3D WARNING] Write PLY failed: mesh has 0 vertices.
Finished.
Saving trajectory to output.log...
Finished.

### Open3D, Python and System information

```markdown
- Operating system: ubunt 20.04
- Python version: Python 3.8.10
- Open3D version: 0.14.1+f6ab689b5
- System type: x84 
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.3
```

### Additional information

Data from l515 as tested against ./dense_slam_gui.py
[roomA_trunc.zip](https://github.com/isl-org/Open3D/files/7978020/roomA_trunc.zip)

**Comment by theNded** [comment]
I have identified the issue. It was caused by the missing scale factor in the pipeline: https://github.com/isl-org/Open3D/blob/6aa17206f273df77c54f11b6efc97aef125d5517/cpp/open3d/t/pipelines/slam/Model.cpp#L111
It will be formally fixed in #4670. Temporarily you may change this line to
```
voxel_grid_.Integrate(frustum_block_coords_, depth, color, intrinsic, extrinsic, depth_scale, depth_max);
```
and recompile the system by `make install-pip-package`. After the fix here is the output:
![image](https://user-images.githubusercontent.com/6127282/151999731-60c4c9cf-82e4-443c-8a0b-2a9aafb2fd64.png)

**Comment by olagt** [comment]
Thank you very much ! 
Now it works :)

**Comment by JomanaAshraf** [comment]
Hii @theNded, 

I am trying to use the dense_slam_gui.py with my dataset which is captured with intel realsense D435 and I stored the color and depth images and also the camera intrinsics as required then I create a config file and named it as "realsense_config.yml"as shown here:
```
name: Default reconstruction system config
fragment_size: 100
device: CUDA:0
engine: tensor
multiprocessing: false
path_dataset: '/home/jomana/masters_ws/src/Studying/Thesis/reconstruction_folder'
depth_folder: depth
color_folder: color
path_intrinsic: '/home/jomana/masters_ws/src/Studying/Thesis/reconstruction_folder/camera_intrinsic.json'
depth_min: 0.1
depth_max: 3.0
depth_scale: 1000.0
odometry_method: hybrid
odometry_loop_interval: 10
odometry_loop_weight: 0.1
odometry_distance_thr: 0.07
icp_method: colored
icp_voxelsize: 0.05
icp_distance_thr: 0.07
global_registration_method: ransac
registration_loop_weight: 0.1
integration_mode: color
voxel_size: 0.0058
trunc_voxel_multiplier: 8.0
block_count: 40000
surface_weight_thr: 3.0
```
but when I excute the code by running this command:
```
python dense_slam_gui.py --config /home/jomana/masters_ws/src/Studying/Thesis/Open3D/examples/python/t_reconstruction_system/realsense_config.yml --device "CPU:0"
```
It gives me this error as the depth and color images are not seen by the code:

> File "dense_slam_gui.py", line 331, in update_main
> depth_ref = o3d.t.io.read_image(depth_file_names[0])
> IndexError: list index out of range


I tried to print the number of files but it gives me 0 
so can you tell me what is the problem with this and why It couldn't process my  own dataset?
